### ISSUE TITLE
Deprecated: mb_convert_encoding(): 

### ISSUE THREAD

**Issue by Whichbfj28** [Victrid/freshrss-image-cache-plugin#3]
Deprecated: mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in freshrss-image-cache-plugin-0.3/extension.php on line 114

 php 8.2.7

**Comment by Victrid** [comment]
Hello, 

I will be updating this plugin to match the code changes in the original plugin:

https://github.com/FreshRSS/Extensions/blob/70c1d7526f26eb444deab5441a04ab3542c244eb/xExtension-ImageProxy/extension.php

Thanks for the Issue!

**Comment by Victrid** [comment]
Problem fixed by #5, and a new version is released.

The original extension also have this problem: https://github.com/FreshRSS/Extensions/issues/225, and I have used a hack from SO, now it would have a harmless extra meta tag for each article:

![Dirty hack](https://github.com/Victrid/freshrss-image-cache-plugin/assets/39787044/6b0a5db6-87de-4adc-9e94-e2e41833ce9a)

But no more deprecation warnings :hugs:  

If you encountered any problem especially in encoding error, please open a new issue.
